[project]
name = "link_budget_calculator"
version = "0.1.0"
description = "Tool for calculating the link budget of transmissions and ."
authors = [
    {name = "Clemens Sonnleitner", email="clemens.sonnleitner@web.de"}
]
maintainers = [
    {name = "Clemens Sonnleitner", email="clemens.sonnleitner@web.de"}  
]
readme = "README.md"
keywords = ["signal", "attenuation", "frequency", "noise"]
requires-python = ">=3.11,<3.14"
dependencies = [
    "numpy >=2.0.0",
    "marimo >=0.10.1",
    "altair >=5.5.0",
    "pandas >=2.2.3",
    "scipy >=1.15.1",
    "pyarrow (>=20.0.0,<21.0.0)",
]

[project.urls]
# Homepage = ""
# Documentation = ""
Repository = "https://github.com/q-wertz/link_budget"
Issues = "https://github.com/q-wertz/link_budget/issues"
# Changelog = ""

[dependency-groups]
dev = [
    "basedpyright>=1.40.1",
    "docformatter>=1.7.8",
    "pandas-stubs>=3.0.5.260914",
    "ruff>=0.16.8",
    "ty>=0.0.82",
]


[tool.marimo]
# Config for 'marimo'
# See `marimo config describe` for more details
[tool.marimo.completion]
activate_on_typing = true
copilot = false

[tool.marimo.formatting]
line_length = 100

[tool.marimo.package_manager]
manager = "uv"


[tool.basedpyright]
# Config for 'basedpyright'
# See https://docs.basedpyright.com for more details
typeCheckingMode = "standard"  # TODO: Set to "recommended" or "all" (but reports many errors)
useLibraryCodeForTypes = false


[tool.pydocstyle]
# Config for 'pydocstyle'
# See http://www.pydocstyle.org/en/stable/usage.html for more details
convention = "numpy"
# Ignore the notes folder and all dirs that start with a dot
match-dir = '[^\.|notes\/].*'


[tool.docformatter]
# Config for the autoformatter for docstrings 'docformatter'
# See https://docformatter.readthedocs.io/en/latest/configuration.html for more details
recursive = true
in-place = true
wrap-summaries = 120
wrap-descriptions = 100


[tool.ruff]
# Config for 'ruff'
# See https://docs.astral.sh/ruff/
# Exclude the following directories
#exclude = ["notes"]
line-length = 100

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
